# Generated by Django 5.1.3 on 2024-12-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
