# Generated by Django 5.1.3 on 2024-12-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
